#!/usr/bin/env bash
# Re-capture the current machine's state back into the repo, so hand-made
# tweaks stop getting lost. Run it, then `git diff` to review.

set -uo pipefail
cd "$(dirname "$0")/.."
source ./scripts/utils.sh

if command_exists code; then
    log_info "Capturing VS Code extensions..."
    { echo "# Regenerated by scripts/capture.sh"; code --list-extensions; } > config/extensions.txt
fi

if [ -f "$HOME/.config/Code/User/settings.json" ]; then
    log_info "Capturing VS Code settings..."
    cp "$HOME/.config/Code/User/settings.json" config/settings.json
fi

if command_exists flatpak; then
    log_info "Capturing flatpak apps..."
    { echo "# Flatpak application IDs installed from Flathub"
      flatpak list --app --columns=application; } > config/flatpaks.txt
fi

if command_exists dconf; then
    log_info "Capturing GNOME Shell and terminal settings..."
    dconf dump /org/gnome/shell/extensions/ > config/gnome-shell.dconf
    dconf dump /org/gnome/Ptyxis/ > config/ptyxis.dconf
    mkdir -p config/personal
    dconf dump /org/gnome/shell/ > config/personal/gnome-shell.dconf
fi

if command_exists gnome-extensions; then
    log_info "Enabled extensions — add new ones to EXTENSIONS in install/desktop.sh:"
    gnome-extensions list --enabled | sed 's/^/  /'
fi

log_success "Captured. Review with: git diff"
